### ISSUE TITLE
[Bug] config.toml文件在运行时重置为默认配置

### ISSUE THREAD

**Issue by xiaofeng96301** [shishanyue/RW-RJR-Server#1]
1. config.toml文件在运行时会重置为默认配置
  PowerShell和cmd启动都会重置回默认，但启动时是重置前端口
2. cmd路径启动或Shell路径启动程序时会默认储存在用户文件夹根目录内
3. 想要简化二级窗口（

**Comment by zerodegress** [comment]
建议在专用工作文件夹下运行RJR，如果直接双击运行配置文件，工作目录可能在C:\Users\Administrator或者一般用户目录，导致配置文件会存储在错误的位置。

**Comment by zerodegress** [comment]
已于#7中解决
